# Generated by Django 6.0.1 on 2026-01-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0005_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('unique_key__isnull', False)), fields=('unique_key', 'channel'), name='unique_notification_per_channel'),
        ),
    ]
